export const getExpirationEmailTemplate = (
  certName: string,
  certNo: string,
  authority: string,
  expiryDate: string,
  daysLeft: number,
  status: string
): string => {
  const statusColor = daysLeft <= 0 ? '#EF4444' : '#F59E0B';
  const statusText = daysLeft <= 0 ? 'EXPIRED' : `EXPIRING IN ${daysLeft} DAYS`;
  const appUrl = 'https://abhyuday-industries-management-system.onrender.com/';

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Compliance Expiration Alert</title>
      <style>
        body { font-family: 'Inter', Helvetica, Arial, sans-serif; background-color: #F3F4F6; margin: 0; padding: 20px; color: #1F2937; }
        .container { max-width: 600px; background-color: #FFFFFF; border-radius: 12px; padding: 30px; margin: 0 auto; box-shadow: 0 4px 6px rgba(0,0,0,0.05); }
        .header { text-align: center; border-bottom: 1px solid #E5E7EB; padding-bottom: 20px; }
        .logo { font-size: 24px; font-weight: bold; color: #3B82F6; text-decoration: none; }
        .badge { display: inline-block; padding: 6px 12px; border-radius: 9999px; font-size: 12px; font-weight: bold; color: #FFFFFF; background-color: ${statusColor}; margin-top: 15px; }
        .content { padding: 20px 0; line-height: 1.6; }
        .table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        .table th, .table td { padding: 12px; border: 1px solid #E5E7EB; text-align: left; }
        .table th { background-color: #F9FAFB; font-weight: 600; }
        .btn { display: inline-block; background-color: #3B82F6; color: #FFFFFF !important; font-weight: 600; padding: 12px 24px; border-radius: 8px; text-decoration: none; text-align: center; margin-top: 20px; }
        .footer { text-align: center; font-size: 12px; color: #9CA3AF; margin-top: 30px; border-top: 1px solid #E5E7EB; padding-top: 20px; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <a href="${appUrl}" class="logo">Abhyuday Industries Management System</a>
          <div><span class="badge">${statusText}</span></div>
        </div>
        <div class="content">
          <p>Hello Compliance Officer,</p>
          <p>This is an automated alert to notify you that the following certificate has reached a compliance milestone and requires immediate review.</p>
          
          <table class="table">
            <tr>
              <th>Certificate Name</th>
              <td>${certName}</td>
            </tr>
            <tr>
              <th>Certificate Number</th>
              <td>${certNo}</td>
            </tr>
            <tr>
              <th>Expiry Date</th>
              <td>${expiryDate}</td>
            </tr>
            <tr>
              <th>Days Remaining</th>
              <td><strong>${daysLeft <= 0 ? 'Expired' : daysLeft}</strong></td>
            </tr>
          </table>

          <p>Please update or renew this certificate as soon as possible to maintain enterprise compliance guidelines.</p>
          <div style="text-align: center;">
            <a href="https://abhyuday-industries-management-system.onrender.com/" class="btn">Manage Certificates</a>
          </div>
        </div>
        <div class="footer">
          <p>This email was automatically generated by Abhyuday Industries Management System.<br>Do not reply directly to this mail.</p>
        </div>
      </div>
    </body>
    </html>
  `;
};

export const getMeetingEmailTemplate = (
  title: string,
  date: string,
  time: string,
  duration: string | undefined,
  location: string,
  description: string,
  organizerName: string,
  emailType: 'morning' | 'time' | 'invitation' = 'invitation'
): string => {
  let headerTitle = 'Compliance Discussion Scheduled';
  let bannerMessage = 'You have been invited to a compliance meeting scheduled by';
  if (emailType === 'morning') {
    headerTitle = '☀️ Morning Reminder: Compliance Meeting Today';
    bannerMessage = 'This is your morning reminder for a compliance meeting scheduled for today by';
  } else if (emailType === 'time') {
    headerTitle = '🔔 Meeting Starting Now!';
    bannerMessage = 'Your scheduled compliance meeting is starting now, organized by';
  }

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>${headerTitle}</title>
      <style>
        body { font-family: 'Inter', Helvetica, Arial, sans-serif; background-color: #F3F4F6; margin: 0; padding: 20px; color: #1F2937; }
        .container { max-width: 600px; background-color: #FFFFFF; border-radius: 12px; padding: 30px; margin: 0 auto; box-shadow: 0 4px 6px rgba(0,0,0,0.05); }
        .header { text-align: center; border-bottom: 1px solid #E5E7EB; padding-bottom: 20px; }
        .logo { font-size: 24px; font-weight: bold; color: #3B82F6; text-decoration: none; }
        .content { padding: 20px 0; line-height: 1.6; }
        .table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        .table th, .table td { padding: 12px; border: 1px solid #E5E7EB; text-align: left; }
        .table th { background-color: #F9FAFB; font-weight: 600; }
        .btn { display: inline-block; background-color: #10B981; color: #FFFFFF !important; font-weight: 600; padding: 12px 24px; border-radius: 8px; text-decoration: none; text-align: center; margin-top: 20px; }
        .footer { text-align: center; font-size: 12px; color: #9CA3AF; margin-top: 30px; border-top: 1px solid #E5E7EB; padding-top: 20px; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <a href="#" class="logo">Abhyuday Management System</a>
          <h3>${headerTitle}</h3>
        </div>
        <div class="content">
          <p>Hello Team member,</p>
          <p>${bannerMessage} <strong>${organizerName}</strong>.</p>
          
          <table class="table">
            <tr>
              <th>Meeting Title</th>
              <td>${title}</td>
            </tr>
            <tr>
              <th>Date</th>
              <td>${date}</td>
            </tr>
            <tr>
              <th>Time</th>
              <td>${time}</td>
            </tr>
            ${duration ? `<tr><th>Duration</th><td>${duration}</td></tr>` : ''}
            <tr>
              <th>Location/Link</th>
              <td>${location}</td>
            </tr>
            ${description ? `<tr><th>Description</th><td>${description}</td></tr>` : ''}
          </table>

          <div style="text-align: center;">
            <a href="${process.env.FRONTEND_URL || 'http://localhost:5173'}/meetings" class="btn">View in Meetings Page</a>
          </div>
        </div>
        <div class="footer">
          <p>This email was automatically generated by Abhyuday Management System.<br>Do not reply directly to this mail.</p>
        </div>
      </div>
    </body>
    </html>
  `;
};

export const getLoginNotificationTemplate = (
  userName: string,
  userEmail: string,
  loginTime: string,
  ipAddress: string,
  userAgent: string,
  role: string
): string => {
  const formattedRole = role.replace('_', ' ').toUpperCase();
  
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Security Alert: New Account Sign-in</title>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #0F172A; margin: 0; padding: 24px 12px; color: #334155; }
        .wrapper { max-width: 600px; margin: 0 auto; background-color: #FFFFFF; border-radius: 16px; overflow: hidden; box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.3), 0 10px 10px -5px rgba(0, 0, 0, 0.2); }
        .header-banner { background: linear-gradient(135deg, #1E293B 0%, #0F172A 100%); padding: 36px 30px; text-align: center; border-bottom: 3px solid #2563EB; }
        .logo-text { font-size: 26px; font-weight: 800; color: #FFFFFF; letter-spacing: -0.5px; text-decoration: none; display: inline-block; }
        .sub-logo { font-size: 11px; text-transform: uppercase; letter-spacing: 2px; color: #94A3B8; margin-top: 4px; font-weight: 600; }
        .badge { display: inline-block; padding: 6px 16px; border-radius: 20px; font-size: 12px; font-weight: 700; color: #10B981; background-color: rgba(16, 185, 129, 0.15); border: 1px solid rgba(16, 185, 129, 0.3); margin-top: 18px; }
        .content { padding: 32px 30px; }
        .greeting { font-size: 18px; font-weight: 700; color: #1E293B; margin-bottom: 12px; }
        .intro-text { font-size: 14px; line-height: 1.6; color: #475569; margin-bottom: 24px; }
        .details-card { background-color: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 12px; padding: 20px; margin-bottom: 24px; }
        .details-title { font-size: 13px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; color: #64748B; margin-bottom: 14px; border-bottom: 1px solid #E2E8F0; padding-bottom: 8px; }
        .detail-row { display: table; width: 100%; padding: 6px 0; font-size: 14px; }
        .detail-label { display: table-cell; width: 35%; color: #64748B; font-weight: 600; }
        .detail-value { display: table-cell; width: 65%; color: #0F172A; font-weight: 600; font-family: monospace; word-break: break-all; }
        .alert-box { background-color: #EFF6FF; border-left: 4px solid #2563EB; border-radius: 8px; padding: 16px; margin-bottom: 28px; }
        .alert-box p { font-size: 13px; line-height: 1.5; color: #1E40AF; margin: 0; }
        .btn-container { text-align: center; margin-top: 24px; margin-bottom: 12px; }
        .btn { display: inline-block; background-color: #2563EB; color: #FFFFFF !important; font-weight: 700; font-size: 14px; padding: 14px 32px; border-radius: 10px; text-decoration: none; box-shadow: 0 4px 12px rgba(37, 99, 235, 0.3); transition: all 0.2s ease; }
        .footer { background-color: #F1F5F9; text-align: center; padding: 24px 30px; font-size: 12px; color: #94A3B8; border-top: 1px solid #E2E8F0; }
        .footer p { margin: 4px 0; line-height: 1.5; }
      </style>
    </head>
    <body>
      <div class="wrapper">
        <div class="header-banner">
          <div class="logo-text">🛡️ Abhyuday Management System</div>
          <div class="sub-logo">Enterprise Security System</div>
          <div><span class="badge">✓ Successful Sign-in</span></div>
        </div>
        <div class="content">
          <div class="greeting">Hello ${userName},</div>
          <p class="intro-text">
            We detected a successful sign-in to your <strong>Abhyuday Management System</strong> account.
            As part of our commitment to account security, a notification is dispatched to your registered email address every time your account is accessed.
          </p>

          <div class="details-card">
            <div class="details-title">Sign-in Activity Summary</div>
            <div class="detail-row">
              <span class="detail-label">Account Email:</span>
              <span class="detail-value" style="font-family: inherit;">${userEmail}</span>
            </div>
            <div class="detail-row">
              <span class="detail-label">Assigned Role:</span>
              <span class="detail-value" style="font-family: inherit;">${formattedRole}</span>
            </div>
            <div class="detail-row">
              <span class="detail-label">Timestamp:</span>
              <span class="detail-value">${loginTime}</span>
            </div>
            <div class="detail-row">
              <span class="detail-label">IP Address:</span>
              <span class="detail-value">${ipAddress}</span>
            </div>
            <div class="detail-row">
              <span class="detail-label">User Agent:</span>
              <span class="detail-value" style="font-size: 12px;">${userAgent}</span>
            </div>
          </div>

          <div class="alert-box">
            <p><strong>🔒 Security Advisory:</strong> If this sign-in was performed by you, no further action is required. If you did not log in, please reset your password immediately to protect your account data.</p>
          </div>

          <div class="btn-container">
            <a href="${process.env.FRONTEND_URL || 'http://localhost:5173'}/login" class="btn">Access Security Portal</a>
          </div>
        </div>
        <div class="footer">
          <p>This automated security notification was sent directly to <strong>${userEmail}</strong>.</p>
          <p>© 2026 Abhyuday Management System. All rights reserved.</p>
        </div>
      </div>
    </body>
    </html>
  `;
};

export const getStabilityEmailTemplate = (
  productName: string,
  batchNumber: string,
  intervalLabel: string,
  dueDateFormatted: string,
  emailType: 'one_day_before' | 'due_today'
): string => {
  const isOneDayBefore = emailType === 'one_day_before';
  const badgeText = isOneDayBefore ? 'DUE TOMORROW' : 'DUE TODAY';
  const badgeColor = isOneDayBefore ? '#F59E0B' : '#EF4444';
  const subjectHeader = isOneDayBefore
    ? 'Upcoming Stability Study Reminder'
    : 'Stability Study Due Today';
  const mainMessage = isOneDayBefore
    ? `Your <strong>${intervalLabel} Stability Study</strong> for <strong>${productName}</strong> (Batch: <strong>${batchNumber}</strong>) is scheduled for tomorrow.`
    : `Your <strong>${intervalLabel} Stability Study</strong> for <strong>${productName}</strong> (Batch: <strong>${batchNumber}</strong>) is due today.`;
  const subMessage = isOneDayBefore
    ? 'Please prepare and complete the Stability Data Sheet in advance.'
    : 'Please perform the required testing, upload the Stability Data Sheet, and mark this interval as Completed in Abhyuday Management System.';

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>${subjectHeader}</title>
      <style>
        body { font-family: 'Inter', Helvetica, Arial, sans-serif; background-color: #F3F4F6; margin: 0; padding: 20px; color: #1F2937; }
        .container { max-width: 600px; background-color: #FFFFFF; border-radius: 12px; padding: 30px; margin: 0 auto; box-shadow: 0 4px 6px rgba(0,0,0,0.05); }
        .header { text-align: center; border-bottom: 1px solid #E5E7EB; padding-bottom: 20px; }
        .logo { font-size: 24px; font-weight: bold; color: #3B82F6; text-decoration: none; }
        .badge { display: inline-block; padding: 6px 14px; border-radius: 9999px; font-size: 11px; font-weight: bold; color: #FFFFFF; background-color: ${badgeColor}; margin-top: 15px; text-transform: uppercase; }
        .content { padding: 20px 0; line-height: 1.6; }
        .table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        .table th, .table td { padding: 12px; border: 1px solid #E5E7EB; text-align: left; }
        .table th { background-color: #F9FAFB; font-weight: 600; }
        .btn { display: inline-block; background-color: #3B82F6; color: #FFFFFF !important; font-weight: 600; padding: 12px 24px; border-radius: 8px; text-decoration: none; text-align: center; margin-top: 20px; }
        .footer { text-align: center; font-size: 12px; color: #9CA3AF; margin-top: 30px; border-top: 1px solid #E5E7EB; padding-top: 20px; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <a href="#" class="logo">Abhyuday Management System</a>
          <div><span class="badge">${badgeText}</span></div>
          <h3 style="margin-top: 10px; color: #1E293B;">${subjectHeader}</h3>
        </div>
        <div class="content">
          <p>Hello Quality & Compliance Team,</p>
          <p>${mainMessage}</p>
          
          <table class="table">
            <tr>
              <th>Product Name</th>
              <td><strong>${productName}</strong></td>
            </tr>
            <tr>
              <th>Batch Number</th>
              <td><code>${batchNumber}</code></td>
            </tr>
            <tr>
              <th>Stability Interval</th>
              <td><strong style="color: #2563EB;">${intervalLabel}</strong></td>
            </tr>
            <tr>
              <th>Scheduled Due Date</th>
              <td>${dueDateFormatted}</td>
            </tr>
          </table>

          <p>${subMessage}</p>

          <div style="text-align: center;">
            <a href="${process.env.FRONTEND_URL || 'http://localhost:5173'}/stability" class="btn">Open Stability Reminders</a>
          </div>
        </div>
        <div class="footer">
          <p>This automated stability alert was dispatched by Abhyuday Management System.<br>Do not reply directly to this email.</p>
        </div>
      </div>
    </body>
    </html>
  `;
};

