import ExcelJS from 'exceljs';

export interface EnterpriseExcelColumn {
  header: string;
  key: string;
  width?: number;
  align?: 'left' | 'center' | 'right';
  type?: 'text' | 'number' | 'date' | 'status' | 'badge';
}

export interface SummaryCardItem {
  label: string;
  value: string | number;
  bgColor: string; // HEX e.g. "DCFCE7"
  textColor: string; // HEX e.g. "15803D"
}

export interface EnterpriseReportOptions {
  filename: string;
  sheetName: string;
  reportTitle: string;
  reportSubtitle?: string;
  operatorName?: string;
  columns: EnterpriseExcelColumn[];
  data: Record<string, any>[];
  summaryCards?: SummaryCardItem[];
}

export const generateEnterpriseExcelReport = async (options: EnterpriseReportOptions) => {
  const {
    filename,
    sheetName,
    reportTitle,
    reportSubtitle = 'Enterprise Compliance Record',
    operatorName = 'System Operator',
    columns,
    data,
    summaryCards = [],
  } = options;

  // 1. Create Workbook
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Enterprise Compliance System';
  workbook.lastModifiedBy = operatorName;
  workbook.created = new Date();
  workbook.modified = new Date();

  // 2. Add Worksheet
  const worksheet = workbook.addWorksheet(sheetName || 'Compliance Report', {
    pageSetup: {
      orientation: 'landscape',
      paperSize: 9, // A4
      fitToPage: true,
      fitToWidth: 1,
      fitToHeight: 0,
      showGridLines: true,
    },
  });

  const totalCols = columns.length;

  // Row 1: Report Title (Unmerged to allow native Excel sorting & filtering without merged-cell conflicts)
  const row1 = worksheet.getRow(1);
  row1.height = 24;
  const titleCell = worksheet.getCell('A1');
  titleCell.value = reportTitle.toUpperCase();
  titleCell.font = { name: 'Calibri', size: 14, bold: true, color: { argb: 'FF0F172A' } };
  titleCell.alignment = { vertical: 'middle', horizontal: 'left' };

  // Row 2: Metadata Details Bar
  const row2 = worksheet.getRow(2);
  row2.height = 18;
  const todayStr = new Date().toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' });
  const metaCell = worksheet.getCell('A2');
  metaCell.value = `Generated On: ${todayStr}   |   Generated By: ${operatorName}   |   Total Records: ${data.length}   |   ${reportSubtitle}`;
  metaCell.font = { name: 'Calibri', size: 9, italic: true, color: { argb: 'FF64748B' } };
  metaCell.alignment = { vertical: 'middle', horizontal: 'left' };

  // 3. Table Header Row (Starts at Row 4 for a clean professional report layout)
  const headerRowIndex = 4;
  const headerRow = worksheet.getRow(headerRowIndex);
  headerRow.height = 28;

  columns.forEach((col, idx) => {
    const colLet = XLSX_colLetter(idx + 1);
    const cell = worksheet.getCell(`${colLet}${headerRowIndex}`);
    cell.value = col.header;
    cell.font = { name: 'Calibri', size: 11, bold: true, color: { argb: 'FFFFFFFF' } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0F172A' } }; // Dark Navy
    cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
    cell.border = {
      top: { style: 'medium', color: { argb: 'FF0F172A' } },
      bottom: { style: 'medium', color: { argb: 'FF0F172A' } },
      left: { style: 'thin', color: { argb: 'FF475569' } },
      right: { style: 'thin', color: { argb: 'FF475569' } },
    };
  });

  // 5. Data Rows
  data.forEach((item, rowIdx) => {
    const rIdx = headerRowIndex + 1 + rowIdx;
    const row = worksheet.getRow(rIdx);
    row.height = 20;

    const isZebra = rowIdx % 2 === 1;
    const rowBgColor = isZebra ? 'FFF8FAFC' : 'FFFFFFFF';

    columns.forEach((col, colIdx) => {
      const colLet = XLSX_colLetter(colIdx + 1);
      const cell = worksheet.getCell(`${colLet}${rIdx}`);
      const rawVal = item[col.key];

      cell.font = { name: 'Calibri', size: 10, color: { argb: 'FF1E293B' } };
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: rowBgColor } };
      cell.border = {
        top: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        right: { style: 'thin', color: { argb: 'FFE2E8F0' } },
      };

      if (rawVal === null || rawVal === undefined) {
        cell.value = '';
      } else if (rawVal instanceof Date) {
        cell.value = rawVal.toISOString().split('T')[0];
        cell.alignment = { vertical: 'middle', horizontal: 'center' };
      } else {
        cell.value = rawVal;
        cell.alignment = {
          vertical: 'middle',
          horizontal: col.align || (typeof rawVal === 'number' ? 'right' : 'left'),
          wrapText: col.header.toLowerCase().includes('remark') || col.header.toLowerCase().includes('detail'),
        };
      }

      // Status Colors
      const strVal = String(cell.value || '').toUpperCase();
      if (
        col.type === 'status' ||
        col.header.toLowerCase().includes('status') ||
        col.header.toLowerCase().includes('days')
      ) {
        if (strVal.includes('ACTIVE') || strVal.includes('VALID')) {
          cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFDCFCE7' } };
          cell.font = { name: 'Calibri', size: 10, bold: true, color: { argb: 'FF15803D' } };
          cell.alignment = { vertical: 'middle', horizontal: 'center' };
        } else if (strVal.includes('30 DAYS') || strVal.includes('7 DAYS') || strVal.includes('EXPIRING SOON')) {
          cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFEDD5' } };
          cell.font = { name: 'Calibri', size: 10, bold: true, color: { argb: 'FFC2410C' } };
          cell.alignment = { vertical: 'middle', horizontal: 'center' };
        } else if (strVal.includes('EXPIRED') || strVal.includes('1 DAY')) {
          cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFEE2E2' } };
          cell.font = { name: 'Calibri', size: 10, bold: true, color: { argb: 'FFB91C1C' } };
          cell.alignment = { vertical: 'middle', horizontal: 'center' };
        } else if (strVal.includes('DONE') || strVal.includes('RESOLVED') || strVal.includes('RENEWED')) {
          cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE0F2FE' } };
          cell.font = { name: 'Calibri', size: 10, bold: true, color: { argb: 'FF0369A1' } };
          cell.alignment = { vertical: 'middle', horizontal: 'center' };
        }
      }
    });
  });

  // 6. Auto-calculate Column Widths with Padding
  columns.forEach((col, colIdx) => {
    let maxLen = col.header.length;
    data.forEach((item) => {
      const val = String(item[col.key] || '');
      if (val.length > maxLen) {
        maxLen = val.length;
      }
    });
    const colObj = worksheet.getColumn(colIdx + 1);
    colObj.width = Math.max(maxLen + 4, col.width || 16);
  });

  // 7. Freeze Panes & Strict Auto Filter (Bounded strictly to data table headers)
  worksheet.views = [
    {
      state: 'frozen',
      xSplit: 0,
      ySplit: headerRowIndex,
      showGridLines: true,
    },
  ];

  worksheet.autoFilter = {
    from: { row: headerRowIndex, column: 1 },
    to: { row: headerRowIndex + data.length, column: totalCols },
  };

  // 8. Download File
  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  });

  const fullFilename = filename.endsWith('.xlsx') ? filename : `${filename}.xlsx`;
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fullFilename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
};

function XLSX_colLetter(colIdx: number): string {
  let temp = colIdx;
  let letter = '';
  while (temp > 0) {
    let mod = (temp - 1) % 26;
    letter = String.fromCharCode(65 + mod) + letter;
    temp = Math.floor((temp - mod) / 26);
  }
  return letter;
}
